apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - ../../base/sample-app

images:
  - name: sample-app
    newName: 516341735012.dkr.ecr.af-south-1.amazonaws.com/acme/api-service
    newTag: 6f935928f93cb951b6630a78d3aeebdd4814ff4d

configMapGenerator:
  - name: sample-app-config
    behavior: merge
    literals:
      - CLUSTER=k3s - On-Prem
      - OVERLAY=onprem

patches:
  - patch: |-
      - op: replace
        path: /metadata/labels/cluster
        value: onprem
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: ecr-pull
    target:
      kind: Deployment
      name: sample-app
