apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - ../../base/sample-app

configMapGenerator:
  - name: sample-app-config
    behavior: merge
    literals:
      - APP_ENV=onprem

patches:
  - patch: |-
      - op: replace
        path: /metadata/labels/cluster
        value: onprem
    target:
      kind: Deployment
      name: sample-app
  - path: html-patch.yaml
    target:
      kind: ConfigMap
      name: sample-app-html
