apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - ../../base/sample-app

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /metadata/labels/cluster
        value: cloud
    target:
      kind: Deployment
      name: sample-app
