apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
- ../../base/sample-app

images:
- name: sample-app
  newName: 516341735012.dkr.ecr.af-south-1.amazonaws.com/acme/api-service
  newTag: 4c11e66437b49fb7be7892b1b64b31b25b195dd0

configMapGenerator:
- behavior: merge
  literals:
  - CLUSTER=EKS - af-south-1
  - OVERLAY=cloud
  name: sample-app-config

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
    - op: replace
      path: /metadata/labels/cluster
      value: cloud
  target:
    kind: Deployment
    name: sample-app
