apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  labels:
    tier: infrastructure
spec:
  project: infrastructure
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.6.2
    helm:
      valuesObject:
        deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          storage:
            type: s3
            s3:
              region: af-south-1
            bucketNames:
              chunks: acme-staging-thanos-516341735012
              ruler: acme-staging-thanos-516341735012
              admin: acme-staging-thanos-516341735012
        singleBinary:
          replicas: 1
          persistence:
            enabled: false
          extraVolumes:
            - name: loki-data
              emptyDir: {}
          extraVolumeMounts:
            - name: loki-data
              mountPath: /var/loki
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        grafana-agent-operator:
          enabled: false
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::516341735012:role/acme-staging-loki
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
