apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos-query
  namespace: argocd
  labels:
    tier: infrastructure
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/bytes1inger/platform-engineer-challenge
    targetRevision: platform-demo
    path: gitops/base/thanos-query
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
